/* =====================================================================
   LITTLE CARE - PHASE 7
   Guardian connection + parent DND + parent pause
   ---------------------------------------------------------------------
   STATUS: additive, IDEMPOTENT, safe to execute more than once.

   WHY THIS FILE EXISTS
   Phase 2 created ChildGuardian but never populated it, and Phase 2
   declared MonitorSession.ParentDndUntilUtc / SitterDndUntilUtc and
   ChildGuardian.CanApprovePause as "STORAGE ONLY" (no logic read them).
   Phase 7 gives them meaning and adds the three tables the frozen Phase 7
   rules require:

     GuardianInvitation  a PENDING invitation cannot live in ChildGuardian,
                         because a ChildGuardian row IS monitoring
                         authorization (Phase 3 MonitoringAccess Rule 4):
                         writing a pending row would instantly grant access.
     MonitoringPause      a two-actor state machine (Requester -> Approver)
                         with a server-computed 150s expiry.
     MonitoringDnd        PER-USER DND. The existing session-level
                         ParentDndUntilUtc is a single scalar and cannot
                         represent Mother and Father independently.

   ARCHITECTURE GUARANTEES (unchanged)
   - Database-First / frozen Model1.edmx: NONE of these tables are mapped
     into the EDMX. They are read and written with raw SQL, exactly like
     MonitorSession / ChildGuardian / JobChildren in Phases 2-6.
   - NO new table replaces CryAlert. Pause reuses the Phase 5/6 incident.
   - NO timer: pause expiry and DND expiry are derived from the persisted
     UTC columns on read, never from a background job.
   - Every table is soft-deleted (IsDeleted) and keeps history.
   ===================================================================== */


/* ---------------------------------------------------------------------
   SECTION A - GuardianInvitation
   ---------------------------------------------------------------------
   WHY A SEPARATE TABLE (Option B) AND NOT ChildGuardian
   ChildGuardian represents an ACCEPTED relationship. A pending invitation
   written there would immediately satisfy
   "SELECT ... FROM ChildGuardian WHERE Child_ID=@p AND Parent_ID=@u AND
   IsDeleted=0" and therefore hand the invitee full monitoring access
   before they ever accepted. Overloading IsDeleted=1 for "pending" is
   worse: it collides with soft-delete, so a REJECTED invite would be
   indistinguishable from a DELETED relationship.

   Token handling: a cryptographically random token is generated by the
   service; ONLY its SHA-256 hash is stored (TokenHash). The plaintext is
   never persisted, never logged and never written to MonitorEvent.
   Without a token the invitee would have to be discovered by searching for
   a username, which lets any parent enumerate the user base; the token
   keeps the invitation non-enumerable and non-forgeable.

   IdentifierValue keeps what the inviter TYPED for audit only. It is never
   trusted for authorization - InvitedParent_ID is always resolved
   server-side from the unique Parent.Username / Parent.EmailAddress.
   --------------------------------------------------------------------- */
IF OBJECT_ID('dbo.GuardianInvitation', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.GuardianInvitation (
        GuardianInvitation_ID INT IDENTITY(1,1) NOT NULL,
        Child_ID              INT             NOT NULL,
        InvitedByParent_ID    INT             NOT NULL,
        InvitedParent_ID      INT             NOT NULL,
        IdentifierType        NVARCHAR(20)    NOT NULL,   -- 'Username' | 'Email'
        IdentifierValue       NVARCHAR(150)   NOT NULL,   -- what was typed (audit)
        TokenHash             NVARCHAR(128)   NOT NULL,   -- SHA-256 of the token
        Status                NVARCHAR(20)    NOT NULL
            CONSTRAINT DF_GuardianInvitation_Status DEFAULT ('Pending'),
        CreatedAtUtc          DATETIME        NOT NULL
            CONSTRAINT DF_GuardianInvitation_CreatedAtUtc DEFAULT (GETUTCDATE()),
        ExpiresAtUtc          DATETIME        NOT NULL,
        DecidedAtUtc          DATETIME        NULL,
        DecidedByParent_ID    INT             NULL,
        Relation              NVARCHAR(50)    NULL,       -- applied on accept
        IsDeleted             BIT             NOT NULL
            CONSTRAINT DF_GuardianInvitation_IsDeleted DEFAULT (0),
        CONSTRAINT PK_GuardianInvitation PRIMARY KEY CLUSTERED (GuardianInvitation_ID)
    );
    PRINT 'Created GuardianInvitation.';
END
GO

/* Token hash must be globally unique so an accept can find the row by hash. */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_GuardianInvitation_TokenHash'
               AND object_id = OBJECT_ID('dbo.GuardianInvitation'))
    CREATE UNIQUE NONCLUSTERED INDEX UX_GuardianInvitation_TokenHash
        ON dbo.GuardianInvitation (TokenHash);
GO

/* The invitee's pending-inbox lookup (GET guardian-invitations). */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GuardianInvitation_Parent_Status'
               AND object_id = OBJECT_ID('dbo.GuardianInvitation'))
    CREATE NONCLUSTERED INDEX IX_GuardianInvitation_Parent_Status
        ON dbo.GuardianInvitation (InvitedParent_ID, Status);
GO

/* Per-child duplicate-invitation check. */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_GuardianInvitation_Child_Status'
               AND object_id = OBJECT_ID('dbo.GuardianInvitation'))
    CREATE NONCLUSTERED INDEX IX_GuardianInvitation_Child_Status
        ON dbo.GuardianInvitation (Child_ID, Status);
GO

/* NO foreign keys and NO cascade on purpose.
   The existing monitoring tables (MonitorSession / ChildGuardian / CryAlert)
   carry no FKs either, and a cascading delete from Parent or Child would
   silently destroy monitoring history that the audit trail must keep.
   Referential integrity is enforced in the service layer, which validates
   every referenced id before writing. */
GO


/* ---------------------------------------------------------------------
   SECTION B - MonitoringPause
   ---------------------------------------------------------------------
   WHY A SEPARATE TABLE
   A pause is a state machine with FOUR outcomes (Requested -> Approved |
   Denied | Expired, plus Cancelled) and THREE distinct server-authoritative
   timestamps per episode (requested / decided / start+expiry). It also has
   two actors who must differ. MonitorSession has no pause columns at all,
   and adding six nullable columns there would either bloat the row the
   Phase 4 heartbeat updates on every beat, or encode a state machine in
   columns. One row per pause EPISODE is the minimal honest model.

   PauseStartUtc / PauseExpiresAtUtc are written ONLY at approval, and the
   expiry is ALWAYS server-computed (now + 150s). The client cannot choose a
   duration or an instant.
   --------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MonitoringPause', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MonitoringPause (
        MonitoringPause_ID   INT IDENTITY(1,1) NOT NULL,
        MonitorSession_ID    INT             NOT NULL,
        Job_ID               INT             NOT NULL,
        Child_ID             INT             NOT NULL,
        RequestedByParent_ID INT             NOT NULL,
        Status               NVARCHAR(20)    NOT NULL
            CONSTRAINT DF_MonitoringPause_Status DEFAULT ('Requested'),
        RequestedAtUtc       DATETIME        NOT NULL
            CONSTRAINT DF_MonitoringPause_RequestedAtUtc DEFAULT (GETUTCDATE()),
        DecidedAtUtc         DATETIME        NULL,
        DecidedByParent_ID   INT             NULL,
        PauseStartUtc        DATETIME        NULL,
        PauseExpiresAtUtc    DATETIME        NULL,
        DecidedReason        NVARCHAR(200)   NULL,
        IsDeleted            BIT             NOT NULL
            CONSTRAINT DF_MonitoringPause_IsDeleted DEFAULT (0),
        CONSTRAINT PK_MonitoringPause PRIMARY KEY CLUSTERED (MonitoringPause_ID)
    );
    PRINT 'Created MonitoringPause.';
END
GO

/* Current-pause lookup by session, and the "one approved pause" guard. */
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_MonitoringPause_Session_Status'
               AND object_id = OBJECT_ID('dbo.MonitoringPause'))
    CREATE NONCLUSTERED INDEX IX_MonitoringPause_Session_Status
        ON dbo.MonitoringPause (MonitorSession_ID, Status);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_MonitoringPause_Job_Child_Status'
               AND object_id = OBJECT_ID('dbo.MonitoringPause'))
    CREATE NONCLUSTERED INDEX IX_MonitoringPause_Job_Child_Status
        ON dbo.MonitoringPause (Job_ID, Child_ID, Status);
GO

/* ---------------------------------------------------------------------
   SECTION C - MonitoringDnd  (PER-USER, replaces the session-level scalar)
   ---------------------------------------------------------------------
   WHY A NEW TABLE
   MonitorSession.ParentDndUntilUtc is ONE column for the whole session, so
   "Mother is DND until 21:00" is ambiguous - it cannot say WHICH parent is
   DND, and there is no second parent slot (SitterDndUntilUtc belongs to the
   sitter). The Phase 7 rule is per-user with independent expiry plus mutual
   exclusion, which a session-level scalar structurally cannot express.

   ParentDndUntilUtc / SitterDndUntilUtc are deliberately LEFT IN PLACE
   (not dropped) - legacy code and the EDMX may still reference them, and
   Phase 7 parent DND simply stops using the parent one.

   ROLE is stored for audit/readability only. The owner is ALWAYS the
   authenticated token's UserId; a client-supplied UserId or Role is never
   read.
   --------------------------------------------------------------------- */
IF OBJECT_ID('dbo.MonitoringDnd', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MonitoringDnd (
        MonitoringDnd_ID   INT IDENTITY(1,1) NOT NULL,
        MonitorSession_ID  INT             NOT NULL,
        Job_ID             INT             NOT NULL,
        Child_ID           INT             NOT NULL,
        UserId             INT             NOT NULL,   -- owner, from the token
        Role               NVARCHAR(20)    NOT NULL,   -- audit only, never trusted
        DndUntilUtc        DATETIME        NOT NULL,
        CancelledAtUtc     DATETIME        NULL,       -- soft "off", history kept
        IsDeleted          BIT             NOT NULL
            CONSTRAINT DF_MonitoringDnd_IsDeleted DEFAULT (0),
        CONSTRAINT PK_MonitoringDnd PRIMARY KEY CLUSTERED (MonitoringDnd_ID)
    );
    PRINT 'Created MonitoringDnd.';
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_MonitoringDnd_Session_User'
               AND object_id = OBJECT_ID('dbo.MonitoringDnd'))
    CREATE NONCLUSTERED INDEX IX_MonitoringDnd_Session_User
        ON dbo.MonitoringDnd (MonitorSession_ID, UserId);
GO


/* ---------------------------------------------------------------------
   SECTION D - BACKFILL: Child.Parent_ID -> ChildGuardian
   ---------------------------------------------------------------------
   WHY THIS BACKFILL IS MANDATORY, NOT OPTIONAL
   Phase 2 created ChildGuardian but left it EMPTY while every one of the 29
   children carries Child.Parent_ID. After the Phase 7 security fix the
   escalation fan-out uses ChildGuardian ONLY, so without this backfill NO
   parent would receive a cry escalation and every parent would be denied
   monitoring access with NotGuardian. The backfill is what makes the
   existing families work; it does not grant anybody anything new, because
   those parents were already the child's owner.

   IsPrimary = 1  : mirrors the original primary-parent relationship.
   CanApprovePause = 0 ON PURPOSE: a single-guardian child has nobody else
   to approve a pause with, and the service ALWAYS refuses self-approval
   (Approver != Requester). Giving the owner CanApprovePause = 1 would let
   them approve their own request, which the frozen rule forbids. The
   capability is granted when a SECOND guardian (e.g. the Father) is
   connected through an accepted invitation, where the service assigns
   CanApprovePause = 1 for a Father/Mother relation.
   --------------------------------------------------------------------- */
INSERT INTO dbo.ChildGuardian (Child_ID, Parent_ID, Relation, IsPrimary, CanApprovePause, CreatedAt, IsDeleted)
SELECT c.Child_ID,
       c.Parent_ID,
       NULL,                       -- relation unknown; the owner is not auto-trusted to approve
       1,                          -- IsPrimary
       0,                          -- CanApprovePause: never self-approve
       GETUTCDATE(),
       0
FROM dbo.Child c
WHERE c.IsDeleted = 0
  AND c.Parent_ID IS NOT NULL
  AND c.Parent_ID > 0
  AND NOT EXISTS (SELECT 1 FROM dbo.ChildGuardian g
                  WHERE g.Child_ID = c.Child_ID AND g.Parent_ID = c.Parent_ID);
PRINT 'Backfilled ChildGuardian from Child.Parent_ID (idempotent).';
GO

/* ---------------------------------------------------------------------
   SECTION E - VERIFICATION (read-only)
   --------------------------------------------------------------------- */
SELECT 'Child active'                      AS Check_, CAST(COUNT(*) AS NVARCHAR(20)) AS Value_
FROM dbo.Child WHERE IsDeleted = 0
UNION ALL SELECT 'ChildGuardian rows',      CAST(COUNT(*) AS NVARCHAR(20)) FROM dbo.ChildGuardian
UNION ALL SELECT 'ChildGuardian active',   CAST(COUNT(*) AS NVARCHAR(20)) FROM dbo.ChildGuardian WHERE IsDeleted = 0
UNION ALL SELECT 'GuardianInvitation',      CAST(COUNT(*) AS NVARCHAR(20)) FROM dbo.GuardianInvitation
UNION ALL SELECT 'MonitoringPause',         CAST(COUNT(*) AS NVARCHAR(20)) FROM dbo.MonitoringPause
UNION ALL SELECT 'MonitoringDnd',           CAST(COUNT(*) AS NVARCHAR(20)) FROM dbo.MonitoringDnd
UNION ALL SELECT 'Children w/o guardian',   CAST(CAST(COUNT(*) AS NVARCHAR(20)) AS NVARCHAR(20))
           FROM dbo.Child c
           WHERE c.IsDeleted = 0 AND c.Parent_ID IS NOT NULL
             AND NOT EXISTS (SELECT 1 FROM dbo.ChildGuardian g
                             WHERE g.Child_ID = c.Child_ID AND g.IsDeleted = 0);
GO

/* ---------------------------------------------------------------------
   ROLLBACK STRATEGY
   Phase 7 is purely ADDITIVE, so rollback is a pure drop of the three new
   tables. The ONLY data change is the ChildGuardian backfill, which can be
   reverted precisely: it only inserted rows with IsPrimary = 1,
   CanApprovePause = 0 and Relation IS NULL for (Child_ID, Parent_ID)
   pairs taken from Child.Parent_ID. The statements below reverse exactly
   that and are commented out on purpose - run them only if required.
   ---------------------------------------------------------------------
   DELETE FROM dbo.ChildGuardian
    WHERE IsPrimary = 1 AND CanApprovePause = 0 AND Relation IS NULL
      AND IsDeleted = 0
      AND EXISTS (SELECT 1 FROM dbo.Child c
                  WHERE c.Child_ID = ChildGuardian.Child_ID
                    AND c.Parent_ID = ChildGuardian.Parent_ID);
   DROP TABLE dbo.MonitoringDnd;
   DROP TABLE dbo.MonitoringPause;
   DROP TABLE dbo.GuardianInvitation;
   --------------------------------------------------------------------- */

SET NOCOUNT ON;
GO
